# Generated by Django 5.0.5 on 2024-05-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_alter_vendors_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorders',
            name='on_time_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseorders',
            name='response_time',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Time taken to acknowledge POs in hours', max_digits=8, null=True),
        ),
    ]
