# Generated by Django 5.0.5 on 2024-05-07 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_purchaseorders_on_time_delivery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorders',
            name='on_time_delivery',
        ),
        migrations.RemoveField(
            model_name='purchaseorders',
            name='response_time',
        ),
    ]
