# Generated by Django 5.0.5 on 2024-05-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0004_remove_purchaseorders_on_time_delivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorders',
            name='acknowledgment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorders',
            name='issue_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
