# Generated by Django 5.0.5 on 2024-05-08 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0005_alter_purchaseorders_acknowledgment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorders',
            name='on_time_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchaseorders',
            name='response_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
